version: "3.0"

services:
  websockets-chat-server:
    container_name: websockets-chat-server
    build:
      context: ./server
      dockerfile: ../docker/dockerfiles/Dockerfile.websockets
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - ./server:/app
    depends_on:
      - websockets-chat-mongodb

  websockets-chat-mongodb:
    container_name: websockets-chat-mongodb
    image: mongo
    restart: always
    volumes:
      - ./docker/volumes/mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: golang-websockets-chat

  websockets-chat-web:
    container_name: websockets-chat-web
    build:
      context: ./web
      dockerfile: ../docker/dockerfiles/Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - websockets-chat-server
