version: "3.9"

services:
  websockets-chat-server:
    container_name: websockets-chat-server
    build:
      context: ./server
      dockerfile: ../docker/dockerfiles/dev/Dockerfile.websockets
    ports:
      - "8080:8080"
      - "4040:4040"
    environment:
      MONGO_HOST: websockets-chat-mongodb
    depends_on:
      - websockets-chat-mongodb

  websockets-chat-cron:
    container_name: websockets-chat-cron
    build:
      context: ./server
      dockerfile: ../docker/dockerfiles/dev/Dockerfile.cron
    ports:
      - "4041:4041"
    environment:
      MONGO_HOST: websockets-chat-mongodb
    depends_on:
      - websockets-chat-mongodb

  websockets-chat-mongodb:
    container_name: websockets-chat-mongodb
    image: mongo
    restart: always
    volumes:
      - ./docker/volumes/mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: golang-websockets-chat

  websockets-chat-web:
    container_name: websockets-chat-web
    build:
      context: ./web
      dockerfile: ../docker/dockerfiles/dev/Dockerfile.web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    depends_on:
      - websockets-chat-server
