name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Build websockets-chat-api
        run: |
          docker build -t websockets-chat-api -f ./docker/dockerfiles/dist/Dockerfile.api ./server
          docker tag websockets-chat-api ${{ secrets.DOCKERHUB_USERNAME }}/websockets-chat-api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/websockets-chat-api

      # - name: Build and push the Docker images
      #   run: |
      #     docker-compose -f docker-compose.prod.yml build
      #     docker-compose -f docker-compose.prod.yml push

      # - name: SSH into EC2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_PRIVATE_KEY }}
      #     script: |
      #       cd /home/ubuntu/golang-websockets-chat
      #       git pull
      #       docker-compose -f docker-compose.prod.yml up -d
  # deploy:
  #   needs: build
  #   runs-on: self-hosted
  #   steps:
  #     - name:


